### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DereckR** [jmwri/pubg-php#19]
Hello,

I am trying to use this but not sure how to. I am simply looking to do a .php file on my server that you can add ?user=PlayersName in a single URL that returns some basic stuff. However I can't figure this out. I saw the original person that did pubg-php I think it was and there instructions are not any good either? I am not sure the formatting or how to get this to run?

**Comment by jmwri** [comment]
Hi DereckR,

You can install this library through [composer](https://getcomposer.org/). Composer is a dependency manager for PHP, which means that it manages all of the libraries that your code depends on allowing you to install and update them with one command.

Once you have installed composer you should be able to follow the readme to install and get started with pubg-php.

**Comment by jmwri** [comment]
Hi @DereckR, has this been resolved?
