### ISSUE TITLE
Error sending request 'Unable to parse response'

### ISSUE THREAD

**Issue by andreich1980** [jmwri/pubg-php#23]
I send `$pubg->getAccount($speamId);` request and it throws an exeption `Unable to parse response` on this part of code
```
if ($response->getHeader('Content-Type')[0] != 'application/json') {
    throw new BadResponseException('Unable to parse response', $response->getStatusCode());
}
```
When I check `$response->getHeader('Content-Type')[0]` it equals `application/json; charset=utf-8`.
So I guess the condition should be changed on "str_pos" or something like that.
```
if (strpos($response->getHeader('Content-Type')[0], 'application/json') === false) {
    throw new BadResponseException('Unable to parse response', $response->getStatusCode());
}
```

**Comment by jmwri** [comment]
Could you provide any info on your OS? Are you using guzzle/curl anywhere else in your project?

**Comment by andreich1980** [comment]
I use your package in my Laravel project. And I think that `guzzlehttp/guzzle` is used in laravel dependencies. 
Windows 10, web server - Laragon

**Comment by jmwri** [comment]
Thanks I have just tested myself and PubgTracker has updated their API to return the header you specified. I will make a PR and release soon. Thanks for contributing!

**Comment by andreich1980** [comment]
Thank you for the fast replies! 👍 I found one more problem, I'll open a new issue.
